ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signer_name VARCHAR(255);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signer_phone VARCHAR(30);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS signer_ip VARCHAR(64);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS sign_id VARCHAR(64);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS sign_hash VARCHAR(64);
