ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_purchased BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_sends_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_code_word VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS trial_codes (
  id SERIAL PRIMARY KEY,
  code_word VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
